export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_FAVOURITES = 'GET_FAVOURITES'; //when have user login
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST';
